name: Release Builds

on:
  push:
    tags:
      - "*.*.*"

permissions: read-all

jobs:
  build:
    name: "${{ matrix.target }}"
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        include:
          - { target: x86_64-linux-musl, os: macos-latest }
          - { target: aarch64-linux-musl, os: macos-latest }
          - { target: x86_64-macos, os: macos-15-intel }
          - { target: aarch64-macos, os: macos-latest }
    permissions:
      contents: write
    runs-on: "${{ matrix.os }}"
    env:
      TARGET: ${{ matrix.target }}
      PG_VERSION: REL_16_1
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install zig automake autoconf libtool

      - name: Build psql
        run: ./build.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: psql-${{ matrix.target }}
          path: build/${{ matrix.target }}/psql-*.tar.gz

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ contains(github.ref_name, '-rc') }}
          files: build/${{ matrix.target }}/psql-*.tar.gz
